import Foundation

@objc(WallpaperExtensionXPCProtocol)
protocol WallpaperExtensionXPCProtocol {
    func acquireWithId(_ id: NSObject?, request: NSObject?, reply: @escaping () -> Void)
    func updateWithId(_ id: NSObject?, request: NSObject?, reply: @escaping () -> Void)
    func invalidateWithId(_ id: NSObject?, reply: @escaping () -> Void)
    func snapshotWithId(_ id: NSObject?, reply: @escaping (NSObject?) -> Void)
    func provideSettingsViewModelsWithContentTypes(_ contentTypes: NSObject?, reply: @escaping (NSObject?) -> Void)
    func addChoiceRequestWithChoiceRequest(_ choiceRequest: NSObject?, onBehalfOfProcess: NSObject?, reply: @escaping () -> Void)
    func removeChoiceRequestWithChoiceRequest(_ choiceRequest: NSObject?, reply: @escaping () -> Void)
    func selectedChoicesDidChangeFor(_ id: NSObject?, reply: @escaping () -> Void)
    func invokeContextMenuActionWithMenuItemID(_ menuItemID: NSObject?, groupItemID: NSObject?, reply: @escaping () -> Void)
    func isChoiceDownloadedWith(_ id: NSObject?, reply: @escaping (NSObject?) -> Void)
    func downloadWithChoiceID(_ choiceID: NSObject?, reply: @escaping () -> Void)
    func migrateSelectedChoiceFor(_ id: NSObject?, reply: @escaping () -> Void)
    func migrateFrom(_ from: NSObject?, to: NSObject?, reply: @escaping () -> Void)
    func skipShuffledContentWithId(_ id: NSObject?, reply: @escaping () -> Void)
    func canSkipShuffledContentWithId(_ id: NSObject?, reply: @escaping (NSObject?) -> Void)
    func handleDebugRequestFor(_ id: NSObject?, reply: @escaping () -> Void)
    func handleNotificationWithNamed(_ name: NSObject?, reply: @escaping () -> Void)
    func cancelDownloadFor(_ id: NSObject?, reply: @escaping () -> Void)
    func pauseDownloadFor(_ id: NSObject?, reply: @escaping () -> Void)
    func resumeDownloadFor(_ id: NSObject?, reply: @escaping () -> Void)
    func removeDownloadFor(_ id: NSObject?, reply: @escaping () -> Void)
}
